// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: overlock/crossplane/environment.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Environment
type Environment struct {
	// metadata
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *EnvironmentSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// id
	Id uint64 `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	// creator
	Creator string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7476339719a8cb6, []int{0}
}
func (m *Environment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return m.Size()
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Environment) GetSpec() *EnvironmentSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Environment) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Environment) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// Spec defines the specification of the environment.
type EnvironmentSpec struct {
	// providers
	Providers []uint64 `protobuf:"varint,2,rep,packed,name=providers,proto3" json:"providers,omitempty"`
	// configurations
	Configurations []uint64 `protobuf:"varint,3,rep,packed,name=configurations,proto3" json:"configurations,omitempty"`
	// functions
	Functions  []uint64 `protobuf:"varint,4,rep,packed,name=functions,proto3" json:"functions,omitempty"`
	Registries []uint64 `protobuf:"varint,5,rep,packed,name=registries,proto3" json:"registries,omitempty"`
}

func (m *EnvironmentSpec) Reset()         { *m = EnvironmentSpec{} }
func (m *EnvironmentSpec) String() string { return proto.CompactTextString(m) }
func (*EnvironmentSpec) ProtoMessage()    {}
func (*EnvironmentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7476339719a8cb6, []int{1}
}
func (m *EnvironmentSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnvironmentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnvironmentSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EnvironmentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentSpec.Merge(m, src)
}
func (m *EnvironmentSpec) XXX_Size() int {
	return m.Size()
}
func (m *EnvironmentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentSpec proto.InternalMessageInfo

func (m *EnvironmentSpec) GetProviders() []uint64 {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *EnvironmentSpec) GetConfigurations() []uint64 {
	if m != nil {
		return m.Configurations
	}
	return nil
}

func (m *EnvironmentSpec) GetFunctions() []uint64 {
	if m != nil {
		return m.Functions
	}
	return nil
}

func (m *EnvironmentSpec) GetRegistries() []uint64 {
	if m != nil {
		return m.Registries
	}
	return nil
}

func init() {
	proto.RegisterType((*Environment)(nil), "overlock.crossplane.Environment")
	proto.RegisterType((*EnvironmentSpec)(nil), "overlock.crossplane.EnvironmentSpec")
}

func init() {
	proto.RegisterFile("overlock/crossplane/environment.proto", fileDescriptor_c7476339719a8cb6)
}

var fileDescriptor_c7476339719a8cb6 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4b, 0x03, 0x31,
	0x18, 0x87, 0x9b, 0xeb, 0xb5, 0xda, 0x14, 0x2a, 0xc4, 0x25, 0x88, 0x86, 0xa3, 0xa8, 0xdc, 0xe2,
	0x1d, 0x5a, 0x05, 0x05, 0x27, 0xc1, 0xd1, 0xe5, 0x04, 0x07, 0xb7, 0x34, 0xf7, 0xf6, 0x0c, 0xb6,
	0x49, 0x48, 0xd2, 0x82, 0xdf, 0xc2, 0xc5, 0x6f, 0xe1, 0x07, 0x71, 0xec, 0xe8, 0x28, 0xed, 0x17,
	0x11, 0xaf, 0xf6, 0x0f, 0xe5, 0xc6, 0xfb, 0xdd, 0xf3, 0x3c, 0x19, 0x5e, 0x7c, 0xa2, 0x27, 0x60,
	0x87, 0x5a, 0xbc, 0xa6, 0xc2, 0x6a, 0xe7, 0xcc, 0x90, 0x2b, 0x48, 0x41, 0x4d, 0xa4, 0xd5, 0x6a,
	0x04, 0xca, 0x27, 0xc6, 0x6a, 0xaf, 0xc9, 0xfe, 0x12, 0x4b, 0xd6, 0xd8, 0x41, 0xb7, 0xca, 0x1d,
	0x81, 0xe7, 0x39, 0xf7, 0x7c, 0x21, 0x76, 0x3f, 0x11, 0x6e, 0xdf, 0xaf, 0x73, 0xe4, 0x06, 0xef,
	0x2e, 0x09, 0x8a, 0x22, 0x14, 0xb7, 0x2f, 0x8e, 0x92, 0x8a, 0x76, 0xf2, 0xf0, 0x0f, 0x65, 0x2b,
	0x9c, 0x5c, 0xe3, 0xd0, 0x19, 0x10, 0x34, 0x28, 0xb5, 0xe3, 0x4a, 0x6d, 0xe3, 0xa9, 0x47, 0x03,
	0x22, 0x2b, 0x0d, 0xd2, 0xc1, 0x81, 0xcc, 0x69, 0x23, 0x42, 0x71, 0x98, 0x05, 0x32, 0x27, 0x14,
	0xef, 0x08, 0x0b, 0xdc, 0x6b, 0x4b, 0x9b, 0x11, 0x8a, 0x5b, 0xd9, 0xf2, 0xb3, 0xfb, 0x81, 0xf0,
	0xde, 0x56, 0x83, 0x1c, 0xe2, 0x96, 0xb1, 0x7a, 0x22, 0x73, 0xb0, 0x8e, 0x06, 0x51, 0x3d, 0x0e,
	0xb3, 0xf5, 0x40, 0x4e, 0x71, 0x47, 0x68, 0x35, 0x90, 0xc5, 0xd8, 0x72, 0x2f, 0xb5, 0x72, 0xb4,
	0x5e, 0x22, 0x5b, 0xeb, 0x5f, 0x65, 0x30, 0x56, 0x62, 0x81, 0x84, 0x8b, 0xca, 0x6a, 0x20, 0x0c,
	0x63, 0x0b, 0x85, 0x74, 0xde, 0x4a, 0x70, 0xb4, 0x51, 0xfe, 0xde, 0x58, 0xee, 0x9e, 0xbe, 0x66,
	0x0c, 0x4d, 0x67, 0x0c, 0xfd, 0xcc, 0x18, 0x7a, 0x9f, 0xb3, 0xda, 0x74, 0xce, 0x6a, 0xdf, 0x73,
	0x56, 0x7b, 0xbe, 0x2d, 0xa4, 0x7f, 0x19, 0xf7, 0x13, 0xa1, 0x47, 0xa9, 0xe0, 0x9e, 0x0f, 0xa5,
	0xba, 0xbc, 0x3a, 0xef, 0xa5, 0x1e, 0x9c, 0x3f, 0xe3, 0x46, 0xa6, 0x85, 0x4e, 0xab, 0xee, 0xe4,
	0xdf, 0x0c, 0xb8, 0x7e, 0xb3, 0xbc, 0x52, 0xef, 0x37, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xfc, 0xae,
	0x6a, 0x07, 0x02, 0x00, 0x00,
}

func (m *Environment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Environment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Environment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEnvironment(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if m.Id != 0 {
		i = encodeVarintEnvironment(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x28
	}
	if m.Spec != nil {
		{
			size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEnvironment(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEnvironment(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EnvironmentSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnvironmentSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnvironmentSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Registries) > 0 {
		dAtA4 := make([]byte, len(m.Registries)*10)
		var j3 int
		for _, num := range m.Registries {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintEnvironment(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Functions) > 0 {
		dAtA6 := make([]byte, len(m.Functions)*10)
		var j5 int
		for _, num := range m.Functions {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintEnvironment(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Configurations) > 0 {
		dAtA8 := make([]byte, len(m.Configurations)*10)
		var j7 int
		for _, num := range m.Configurations {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintEnvironment(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Providers) > 0 {
		dAtA10 := make([]byte, len(m.Providers)*10)
		var j9 int
		for _, num := range m.Providers {
			for num >= 1<<7 {
				dAtA10[j9] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j9++
			}
			dAtA10[j9] = uint8(num)
			j9++
		}
		i -= j9
		copy(dAtA[i:], dAtA10[:j9])
		i = encodeVarintEnvironment(dAtA, i, uint64(j9))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func encodeVarintEnvironment(dAtA []byte, offset int, v uint64) int {
	offset -= sovEnvironment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Environment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovEnvironment(uint64(l))
	}
	if m.Spec != nil {
		l = m.Spec.Size()
		n += 1 + l + sovEnvironment(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovEnvironment(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEnvironment(uint64(l))
	}
	return n
}

func (m *EnvironmentSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Providers) > 0 {
		l = 0
		for _, e := range m.Providers {
			l += sovEnvironment(uint64(e))
		}
		n += 1 + sovEnvironment(uint64(l)) + l
	}
	if len(m.Configurations) > 0 {
		l = 0
		for _, e := range m.Configurations {
			l += sovEnvironment(uint64(e))
		}
		n += 1 + sovEnvironment(uint64(l)) + l
	}
	if len(m.Functions) > 0 {
		l = 0
		for _, e := range m.Functions {
			l += sovEnvironment(uint64(e))
		}
		n += 1 + sovEnvironment(uint64(l)) + l
	}
	if len(m.Registries) > 0 {
		l = 0
		for _, e := range m.Registries {
			l += sovEnvironment(uint64(e))
		}
		n += 1 + sovEnvironment(uint64(l)) + l
	}
	return n
}

func sovEnvironment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEnvironment(x uint64) (n int) {
	return sovEnvironment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Environment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEnvironment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Environment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Environment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEnvironment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEnvironment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEnvironment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &Metadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEnvironment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEnvironment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEnvironment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spec == nil {
				m.Spec = &EnvironmentSpec{}
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEnvironment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEnvironment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEnvironment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEnvironment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEnvironment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEnvironment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnvironmentSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEnvironment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnvironmentSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnvironmentSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Providers = append(m.Providers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEnvironment
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEnvironment
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Providers) == 0 {
					m.Providers = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEnvironment
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Providers = append(m.Providers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Configurations = append(m.Configurations, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEnvironment
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEnvironment
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Configurations) == 0 {
					m.Configurations = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEnvironment
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Configurations = append(m.Configurations, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Configurations", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Functions = append(m.Functions, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEnvironment
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEnvironment
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Functions) == 0 {
					m.Functions = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEnvironment
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Functions = append(m.Functions, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Functions", wireType)
			}
		case 5:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Registries = append(m.Registries, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEnvironment
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEnvironment
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEnvironment
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Registries) == 0 {
					m.Registries = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEnvironment
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Registries = append(m.Registries, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Registries", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEnvironment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEnvironment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEnvironment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEnvironment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEnvironment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEnvironment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEnvironment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEnvironment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEnvironment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEnvironment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEnvironment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEnvironment = fmt.Errorf("proto: unexpected end of group")
)
